In [29]:
import numpy as np
import numpy_financial as npf
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf
from sklearn.linear_model import LogisticRegression

# .map('{:,.2f}'.format) - - - for big numbers

In [30]:
df = pd.read_csv('/Users/jakemeissner/Documents/datasets/bank-direct-marketing-campaigns.csv')
df.head(10)

age          job  marital            education  default housing loan  \
0   56    housemaid  married             basic.4y       no      no   no   
1   57     services  married          high.school  unknown      no   no   
2   37     services  married          high.school       no     yes   no   
3   40       admin.  married             basic.6y       no      no   no   
4   56     services  married          high.school       no      no  yes   
5   45     services  married             basic.9y  unknown      no   no   
6   59       admin.  married  professional.course       no      no   no   
7   41  blue-collar  married              unknown  unknown      no   no   
8   24   technician   single  professional.course       no     yes   no   
9   25     services   single          high.school       no     yes   no   

     contact month day_of_week  campaign  pdays  previous     poutcome  \
0  telephone   may         mon         1    999         0  nonexistent   
1  telephone   may         mon         1    999         0  nonexistent   
2  telephone   may         mon         1    999         0  nonexistent   
3  telephone   may         mon         1    999         0  nonexistent   
4  telephone   may         mon         1    999         0  nonexistent   
5  telephone   may         mon         1    999         0  nonexistent   
6  telephone   may         mon         1    999         0  nonexistent   
7  telephone   may         mon         1    999         0  nonexistent   
8  telephone   may         mon         1    999         0  nonexistent   
9  telephone   may         mon         1    999         0  nonexistent   

   emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  nr.employed   y  
0           1.1          93.994          -36.4      4.857       5191.0  no  
1           1.1          93.994          -36.4      4.857       5191.0  no  
2           1.1          93.994          -36.4      4.857       5191.0  no  
3           1.1          93.994          -36.4      4.857       5191.0  no  
4           1.1          93.994          -36.4      4.857       5191.0  no  
5           1.1          93.994          -36.4      4.857       5191.0  no  
6           1.1          93.994          -36.4      4.857       5191.0  no  
7           1.1          93.994          -36.4      4.857       5191.0  no  
8           1.1          93.994          -36.4      4.857       5191.0  no  
9           1.1          93.994          -36.4      4.857       5191.0  no

In [31]:
df.corr()

age  campaign     pdays  previous  emp.var.rate  \
age             1.000000  0.004594 -0.034369  0.024365     -0.000371   
campaign        0.004594  1.000000  0.052584 -0.079141      0.150754   
pdays          -0.034369  0.052584  1.000000 -0.587514      0.271004   
previous        0.024365 -0.079141 -0.587514  1.000000     -0.420489   
emp.var.rate   -0.000371  0.150754  0.271004 -0.420489      1.000000   
cons.price.idx  0.000857  0.127836  0.078889 -0.203130      0.775334   
cons.conf.idx   0.129372 -0.013733 -0.091342 -0.050936      0.196041   
euribor3m       0.010767  0.135133  0.296899 -0.454494      0.972245   
nr.employed    -0.017725  0.144095  0.372605 -0.501333      0.906970   

                cons.price.idx  cons.conf.idx  euribor3m  nr.employed  
age                   0.000857       0.129372   0.010767    -0.017725  
campaign              0.127836      -0.013733   0.135133     0.144095  
pdays                 0.078889      -0.091342   0.296899     0.372605  
previous             -0.203130      -0.050936  -0.454494    -0.501333  
emp.var.rate          0.775334       0.196041   0.972245     0.906970  
cons.price.idx        1.000000       0.058986   0.688230     0.522034  
cons.conf.idx         0.058986       1.000000   0.277686     0.100513  
euribor3m             0.688230       0.277686   1.000000     0.945154  
nr.employed           0.522034       0.100513   0.945154     1.000000

In [32]:
df['education'].unique()

array(['basic.4y', 'high.school', 'basic.6y', 'basic.9y',
       'professional.course', 'unknown', 'university.degree',
       'illiterate'], dtype=object)

In [33]:
df['married'] = df['marital'] == 'married'
df['educated'] = df['education'] == ('basic.4y' or 'basic.6y' or 'basic.9y' or 'professional.course' or 'university.degree')
df['housed'] = df['housing'] == 'yes'
df['no_default'] = df['default'] == 'no'

In [34]:
X = df[['married', 'educated', 'housed', 'no_default']].values
y = df['poutcome'].values

In [35]:
model = LogisticRegression()

In [36]:
model.fit(X, y)

LogisticRegression()

In [37]:
print(model.coef_, model.intercept_)

[[-0.01581168 -0.107644    0.03914193 -0.13788892]
 [ 0.13284767 -0.03295407 -0.0913726  -0.84807334]
 [-0.117036    0.14059807  0.05223067  0.98596227]] [-0.18253626  2.50712809 -2.32459183]


In [38]:
model.predict(X)

array(['nonexistent', 'nonexistent', 'nonexistent', ..., 'nonexistent',
       'nonexistent', 'nonexistent'], dtype=object)

In [39]:
y_pred = model.predict(X)
y == y_pred

array([ True,  True,  True, ...,  True,  True, False])

In [45]:
y.shape[0]

41188

In [46]:
print((y == y_pred).sum() / y.shape[0])

0.8634310964358551


In [47]:
print(model.score(X, y))

0.8634310964358551


In [50]:
df['poutcome'].unique()

array(['nonexistent', 'failure', 'success'], dtype=object)